const nutritionLookup = require('../controllers/nutritionLookup')
const schedule = require('../controllers/schedule')
const target = require('../controllers/target')
const userAuthentication=require('../controllers/userAuthentication')
const userProfile = require('../controllers/userProfile')
const router=require('express').Router()

router.post('/signup',userAuthentication.signUp)
router.get('/login',userAuthentication.logIn)
router.put('/changepassword',userAuthentication.changePassword)
router.post('/profile',userProfile.createUserProfile)
router.put('/profile',userProfile.updateUserProfile)
router.get('/profile',userProfile.getUserProfile)
router.get('/nutritionlookup',nutritionLookup.search)
router.post('/tag',schedule.createTag)
router.get('/session',schedule.getSession)
router.get('/food',nutritionLookup.getFood)
router.get('/tag',schedule.getTag)
router.put('/tag',schedule.updataTag)
router.delete('/tag',schedule.deletaTag)
router.post('/target',target.createTarget)
router.put('/target',target.changeTarget)
router.get('/target',target.getTarget)

module.exports=router